var = getenv('HOME');
sub_dirs = {[var, '/compute/AutismOlfactory/BO606/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO608/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO613/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO618/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO625/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO632/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO656/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO670/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO674/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO676/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO683/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO694/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO695/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO696/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO698/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO699/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO700/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO701/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO703/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO704/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO705/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO706/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO708/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO709/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO710/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO711/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO712/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO915/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO930/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO976/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO999/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1048/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1055/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1063/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1065/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1086/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1104/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1108/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1109/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1115/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1116/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1117/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1118/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1119/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1120/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1121/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1126/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1127/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1128/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1129/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1130/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1131/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1133/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1135/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1136/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1137/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1138/dti_data/dti30trilin/'], ...
[var, '/compute/AutismOlfactory/BO1140/dti_data/dti30trilin/']};
sub_group = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
save('~/compute/AutismOlfactory/Analyses/dtiAnalysis/AFQ/sub_dirs.mat', 'sub_dirs');
save('~/compute/AutismOlfactory/Analyses/dtiAnalysis/AFQ/sub_group.mat', 'sub_group');
quit
